"""공유 DB 적용 후 마스터 161개 스냅샷. 작성자: 김진우."""

from heapy_ocr.models import MasterCheckupItem

CATALOG_SOURCE = "public.master_checkup_item"
CATALOG_ROW_COUNT = 161
# 작성자: 김진우 — 코드순 5개 필드 배열의 UTF-8 JSON SHA-256.
CATALOG_SHA256 = "607202cef5ab2b6c726b0909bf2416fbb984a7954a8e16b7a6a8263b57d01e16"

MASTER_CHECKUP_ITEMS: tuple[MasterCheckupItem, ...] = (
    MasterCheckupItem("ABDOMINAL_CT", "복부 CT", None, "numeric", True),
    MasterCheckupItem("ABO_BLOOD_GROUP", "ABO 혈액형", None, "numeric", True),
    MasterCheckupItem("AFP", "알파태아단백(AFP)", "ng/mL", "numeric", True),
    MasterCheckupItem("AG_RATIO", "알부민/글로불린 비율", None, "numeric", True),
    MasterCheckupItem("ALBUMIN", "알부민", "g/dL", "numeric", True),
    MasterCheckupItem("ALP", "알칼리인산분해효소(ALP)", "U/L", "numeric", True),
    MasterCheckupItem("ALT", "에이엘티(ALT)", "U/L", "numeric", True),
    MasterCheckupItem("AMYLASE", "아밀라아제", "U/L", "numeric", True),
    MasterCheckupItem("AST", "에이에스티(AST)", "U/L", "numeric", True),
    MasterCheckupItem("BASOPHIL_PERCENT", "호염구백분율", "%", "numeric", True),
    MasterCheckupItem("BMI", "체질량지수", "kg/m2", "numeric", True),
    MasterCheckupItem("BODY_FAT_MASS", "체지방량", "kg", "numeric", True),
    MasterCheckupItem("BODY_FAT_PERCENTAGE", "체지방률", "%", "numeric", True),
    MasterCheckupItem("BONE_DENSITY", "골밀도검사", None, "numeric", True),
    MasterCheckupItem("BONE_DENSITY_T_SCORE", "골밀도 T-score", None, "numeric", True),
    MasterCheckupItem("BONE_DENSITY_Z_SCORE", "골밀도 Z-score", None, "numeric", True),
    MasterCheckupItem("BRAIN_MRA", "뇌 MRA", None, "numeric", True),
    MasterCheckupItem("BRAIN_MRI", "뇌 MRI", None, "numeric", True),
    MasterCheckupItem("BREAST_ULTRASOUND", "유방초음파", None, "numeric", True),
    MasterCheckupItem("BUN", "요소질소(BUN)", "mg/dL", "numeric", True),
    MasterCheckupItem("BUN_CREATININE_RATIO", "요소질소/크레아티닌 비율", None, "numeric", True),
    MasterCheckupItem("CA125", "CA 125", "U/mL", "numeric", True),
    MasterCheckupItem("CA19_9", "CA 19-9", "U/mL", "numeric", True),
    MasterCheckupItem("CALCIUM", "칼슘", "mg/dL", "numeric", True),
    MasterCheckupItem("CAPE15", "정신건강검사(조기정신증, CAPE-15)", "score", "numeric", True),
    MasterCheckupItem("CAROTID_ULTRASOUND", "경동맥초음파", None, "numeric", True),
    MasterCheckupItem("CBC_PANEL", "일반혈액검사 패널(CBC)", None, "numeric", True),
    MasterCheckupItem("CEA", "암배아항원(CEA)", "ng/mL", "numeric", True),
    MasterCheckupItem("CERVICAL_CYTOLOGY", "자궁경부 세포검사", None, "numeric", True),
    MasterCheckupItem("CHEST_XRAY", "흉부 X선(촬영 방향 미기재)", None, "text", True),
    MasterCheckupItem("CHEST_XRAY_PA", "흉부방사선 직접촬영(PA)", None, "text", True),
    MasterCheckupItem("CHLORIDE", "염소", "mmol/L", "numeric", True),
    MasterCheckupItem("CK", "크레아틴키나아제(CK)", "U/L", "numeric", True),
    MasterCheckupItem("COLONOSCOPY", "대장내시경", None, "numeric", True),
    MasterCheckupItem("CORONARY_CALCIUM_CT", "관상동맥 석회화 CT", None, "numeric", True),
    MasterCheckupItem("CYFRA21_1", "CYFRA 21-1", "ng/mL", "numeric", True),
    MasterCheckupItem("CYSTATIN_C", "시스타틴 C", "mg/L", "numeric", True),
    MasterCheckupItem("DENTAL_PLAQUE", "치면세균막검사", None, "numeric", True),
    MasterCheckupItem("DIASTOLIC_BP", "이완기혈압", "mmHg", "numeric", True),
    MasterCheckupItem("DIRECT_BILIRUBIN", "직접빌리루빈", "mg/dL", "numeric", True),
    MasterCheckupItem("ECG", "심전도", None, "numeric", True),
    MasterCheckupItem("ECHOCARDIOGRAPHY", "심장초음파", None, "numeric", True),
    MasterCheckupItem("EGFR", "신사구체여과율(e-GFR)", "mL/min/1.73m2", "numeric", True),
    MasterCheckupItem("ELDERLY_PHYSICAL_FUNCTION", "노인신체기능검사", None, "numeric", True),
    MasterCheckupItem("EOSINOPHIL_PERCENT", "호산구백분율", "%", "numeric", True),
    MasterCheckupItem("ESR", "적혈구침강속도", "mm/hr", "numeric", True),
    MasterCheckupItem("ESTRADIOL", "에스트라디올(E2)", "pg/mL", "numeric", True),
    MasterCheckupItem("FASTING_GLUCOSE", "공복혈당", "mg/dL", "numeric", True),
    MasterCheckupItem("FECAL_OCCULT_BLOOD_QUANT", "분변잠혈 정량", None, "numeric", True),
    MasterCheckupItem("FERRITIN", "페리틴", "ng/mL", "numeric", True),
    MasterCheckupItem("FEV1", "1초간 노력성 호기량(FEV1)", "L", "numeric", True),
    MasterCheckupItem("FEV1_FVC_RATIO", "FEV1/FVC 비율", "%", "numeric", True),
    MasterCheckupItem("FIB4", "FIB-4 간섬유화 지수", None, "numeric", True),
    MasterCheckupItem("FREE_T4", "유리티록신(Free T4)", "ng/dL", "numeric", True),
    MasterCheckupItem("FSH", "난포자극호르몬(FSH)", "mIU/mL", "numeric", True),
    MasterCheckupItem("FVC", "노력성 폐활량(FVC)", "L", "numeric", True),
    MasterCheckupItem("GAMMA_GTP", "감마지티피(γ-GTP)", "U/L", "numeric", True),
    MasterCheckupItem("GLOBULIN", "글로불린", "g/dL", "numeric", True),
    MasterCheckupItem("HBA1C", "당화혈색소(HbA1c)", "%", "numeric", True),
    MasterCheckupItem("HDL_CHOLESTEROL", "고밀도(HDL) 콜레스테롤", "mg/dL", "numeric", True),
    MasterCheckupItem("HE4", "HE4", "pmol/L", "numeric", True),
    MasterCheckupItem("HEARING_1000HZ_LEFT", "청력 1000Hz(좌)", "dB", "numeric", True),
    MasterCheckupItem("HEARING_1000HZ_RIGHT", "청력 1000Hz(우)", "dB", "numeric", True),
    MasterCheckupItem("HEARING_GENERAL_LEFT", "일반 청력(좌)", None, "text", True),
    MasterCheckupItem("HEARING_GENERAL_RIGHT", "일반 청력(우)", None, "text", True),
    MasterCheckupItem("HEIGHT", "신장", "cm", "numeric", True),
    MasterCheckupItem("HEMATOCRIT", "헤마토크리트", "%", "numeric", True),
    MasterCheckupItem("HEMOGLOBIN", "혈색소", "g/dL", "numeric", True),
    MasterCheckupItem("HEPATITIS_A_ANTIBODY", "A형간염 항체", None, "numeric", True),
    MasterCheckupItem(
        "HEPATITIS_B_SURFACE_ANTIBODY", "B형간염 표면항체(HBsAb)", None, "numeric", True
    ),
    MasterCheckupItem(
        "HEPATITIS_B_SURFACE_ANTIGEN", "B형간염 표면항원(HBsAg)", None, "numeric", True
    ),
    MasterCheckupItem("HEPATITIS_C_ANTIBODY", "C형간염 항체(HCV Ab)", None, "numeric", True),
    MasterCheckupItem("HIV_AG_AB", "HIV 항원·항체", None, "numeric", True),
    MasterCheckupItem("HPV_TEST", "인유두종바이러스(HPV) 검사", None, "numeric", True),
    MasterCheckupItem("HS_CRP", "고감도 C반응단백(hs-CRP)", "mg/L", "numeric", True),
    MasterCheckupItem("INDIRECT_BILIRUBIN", "간접빌리루빈(계산값)", "mg/dL", "numeric", True),
    MasterCheckupItem("IRON", "혈청철", "ug/dL", "numeric", True),
    MasterCheckupItem("KDSQC", "인지기능장애검사(KDSQ-C)", "score", "numeric", True),
    MasterCheckupItem("LDH", "젖산탈수소효소(LDH)", "U/L", "numeric", True),
    MasterCheckupItem("LDL_CHOLESTEROL", "저밀도(LDL) 콜레스테롤", "mg/dL", "numeric", True),
    MasterCheckupItem("LIFESTYLE_ASSESSMENT", "생활습관평가", None, "numeric", True),
    MasterCheckupItem("LIPASE", "리파아제", "U/L", "numeric", True),
    MasterCheckupItem("LIPID_PANEL", "지질검사 패널", None, "numeric", True),
    MasterCheckupItem("LIVER_FIBROSIS_SCAN", "간 섬유화·지방 스캔", None, "numeric", True),
    MasterCheckupItem("LIVER_FUNCTION_PANEL", "간기능검사 패널", None, "numeric", True),
    MasterCheckupItem("LOW_DOSE_CHEST_CT", "저선량 흉부 CT", None, "numeric", True),
    MasterCheckupItem("LYMPHOCYTE_PERCENT", "림프구백분율", "%", "numeric", True),
    MasterCheckupItem("MAGNESIUM", "마그네슘", "mg/dL", "numeric", True),
    MasterCheckupItem("MAMMOGRAPHY", "유방촬영", None, "numeric", True),
    MasterCheckupItem("MCH", "평균적혈구혈색소", "pg", "numeric", True),
    MasterCheckupItem("MCHC", "평균적혈구혈색소농도", "g/dL", "numeric", True),
    MasterCheckupItem("MCV", "평균적혈구용적", "fL", "numeric", True),
    MasterCheckupItem("MEDICAL_INTERVIEW_CONSULTATION", "문진·진찰 및 상담", None, "numeric", True),
    MasterCheckupItem("METABOLIC_AGE", "대사생체나이", "year", "numeric", True),
    MasterCheckupItem("MONOCYTE_PERCENT", "단핵구백분율", "%", "numeric", True),
    MasterCheckupItem("MPV", "평균혈소판용적", "fL", "numeric", True),
    MasterCheckupItem("MUSCLE_MASS", "근육량", "kg", "numeric", True),
    MasterCheckupItem("NEUTROPHIL_PERCENT", "호중구백분율", "%", "numeric", True),
    MasterCheckupItem("ORAL_EXAM", "구강검진", None, "numeric", True),
    MasterCheckupItem("OXYGEN_SATURATION", "산소포화도", "%", "numeric", True),
    MasterCheckupItem("PCT", "혈소판백분율", "%", "numeric", True),
    MasterCheckupItem("PDW", "혈소판분포계수", "fL", "numeric", True),
    MasterCheckupItem("PELVIC_ULTRASOUND", "부인과초음파", None, "numeric", True),
    MasterCheckupItem("PHOSPHORUS", "인", "mg/dL", "numeric", True),
    MasterCheckupItem("PHQ9", "정신건강검사(우울증, PHQ-9)", "score", "numeric", True),
    MasterCheckupItem("PLATELET_COUNT", "혈소판수", "10^3/uL", "numeric", True),
    MasterCheckupItem("POTASSIUM", "칼륨", "mmol/L", "numeric", True),
    MasterCheckupItem("PROSTATE_ULTRASOUND", "전립선초음파", None, "numeric", True),
    MasterCheckupItem("PSA", "전립선특이항원(PSA)", "ng/mL", "numeric", True),
    MasterCheckupItem("PULMONARY_FUNCTION", "폐기능검사", None, "numeric", True),
    MasterCheckupItem("PULSE", "맥박", "/min", "numeric", True),
    MasterCheckupItem("RBC_COUNT", "적혈구수", "10^6/uL", "numeric", True),
    MasterCheckupItem("RDW", "적혈구분포계수", "%", "numeric", True),
    MasterCheckupItem("RH_BLOOD_GROUP", "Rh 혈액형", None, "numeric", True),
    MasterCheckupItem("RHEUMATOID_FACTOR", "류마티스인자(RF)", "IU/mL", "numeric", True),
    MasterCheckupItem("ROMA_SCORE", "ROMA 점수", "%", "numeric", True),
    MasterCheckupItem("SERUM_CREATININE", "혈청크레아티닌", "mg/dL", "numeric", True),
    MasterCheckupItem("SODIUM", "나트륨", "mmol/L", "numeric", True),
    MasterCheckupItem("STOOL_PARASITE_SMEAR", "분변 기생충 도말검사", None, "numeric", True),
    MasterCheckupItem("STRESS_ASSESSMENT", "스트레스 평가", None, "numeric", True),
    MasterCheckupItem("SYPHILIS_SCREEN", "매독 선별검사", None, "numeric", True),
    MasterCheckupItem("SYSTOLIC_BP", "수축기혈압", "mmHg", "numeric", True),
    MasterCheckupItem("T3", "트리요오드티로닌(T3)", "ng/dL", "numeric", True),
    MasterCheckupItem("TESTOSTERONE", "테스토스테론", "ng/dL", "numeric", True),
    MasterCheckupItem("THYROID_FUNCTION_PANEL", "갑상선기능검사 패널", None, "numeric", True),
    MasterCheckupItem("THYROID_ULTRASOUND", "갑상선초음파", None, "numeric", True),
    MasterCheckupItem("TIBC", "총철결합능(TIBC)", "ug/dL", "numeric", True),
    MasterCheckupItem("TOTAL_BILIRUBIN", "총빌리루빈", "mg/dL", "numeric", True),
    MasterCheckupItem("TOTAL_CHOLESTEROL", "총콜레스테롤", "mg/dL", "numeric", True),
    MasterCheckupItem("TOTAL_PROTEIN", "총단백", "g/dL", "numeric", True),
    MasterCheckupItem("TRIGLYCERIDES", "중성지방", "mg/dL", "numeric", True),
    MasterCheckupItem("TSH", "갑상선자극호르몬(TSH)", "uIU/mL", "numeric", True),
    MasterCheckupItem("UIBC", "불포화철결합능(UIBC)", "ug/dL", "numeric", True),
    MasterCheckupItem("UPPER_ABDOMINAL_ULTRASOUND", "상복부초음파", None, "numeric", True),
    MasterCheckupItem("UPPER_GI_ENDOSCOPY", "일반 위내시경", None, "numeric", True),
    MasterCheckupItem("UPPER_GI_SERIES", "위장조영촬영", None, "numeric", True),
    MasterCheckupItem("URIC_ACID", "요산", "mg/dL", "numeric", True),
    MasterCheckupItem("URINALYSIS_PANEL", "요검사 패널", None, "numeric", True),
    MasterCheckupItem("URINE_BILIRUBIN", "요빌리루빈", None, "numeric", True),
    MasterCheckupItem("URINE_GLUCOSE", "요당", None, "numeric", True),
    MasterCheckupItem("URINE_KETONE", "요케톤체", None, "numeric", True),
    MasterCheckupItem("URINE_LEUKOCYTE", "요백혈구", None, "numeric", True),
    MasterCheckupItem(
        "URINE_MICROALBUMIN_CREATININE_RATIO",
        "요미세알부민/크레아티닌 비율",
        "mg/g",
        "numeric",
        True,
    ),
    MasterCheckupItem("URINE_NITRITE", "요아질산염", None, "numeric", True),
    MasterCheckupItem("URINE_OCCULT_BLOOD", "요잠혈", None, "numeric", True),
    MasterCheckupItem("URINE_PH", "요산도", None, "numeric", True),
    MasterCheckupItem("URINE_PROTEIN", "요단백", None, "numeric", True),
    MasterCheckupItem("URINE_SEDIMENT_BACTERIA", "요침사 세균", None, "numeric", True),
    MasterCheckupItem("URINE_SEDIMENT_CAST", "요침사 원주", "/LPF", "numeric", True),
    MasterCheckupItem("URINE_SEDIMENT_EPITHELIAL_CELL", "요침사 상피세포", "/HPF", "numeric", True),
    MasterCheckupItem("URINE_SEDIMENT_OTHER", "요침사 기타", None, "numeric", True),
    MasterCheckupItem("URINE_SEDIMENT_RBC", "요침사 적혈구", "/HPF", "numeric", True),
    MasterCheckupItem("URINE_SEDIMENT_WBC", "요침사 백혈구", "/HPF", "numeric", True),
    MasterCheckupItem("URINE_SPECIFIC_GRAVITY", "요비중", None, "numeric", True),
    MasterCheckupItem("URINE_UROBILINOGEN", "요유로빌리노겐", None, "numeric", True),
    MasterCheckupItem("VISUAL_ACUITY_LEFT", "시력(좌)", None, "numeric", True),
    MasterCheckupItem("VISUAL_ACUITY_RIGHT", "시력(우)", None, "numeric", True),
    MasterCheckupItem("VITAMIN_D_25_OH", "25-OH 비타민D", "ng/mL", "numeric", True),
    MasterCheckupItem("WAIST_CIRCUMFERENCE", "허리둘레", "cm", "numeric", True),
    MasterCheckupItem("WBC_COUNT", "백혈구수", "10^3/uL", "numeric", True),
    MasterCheckupItem("WEIGHT", "체중", "kg", "numeric", True),
)
